#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unsafe_op_in_unsafe_fn)]
#![allow(clippy::useless_transmute)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::ptr_offset_with_cast)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::suspicious_doc_comments)]
include!(concat!(env!("OUT_DIR"), "/bindings_libcsp.rs"));
